## Importar Librerias

In [7]:
import janitor
import matplotlib.pyplot as plt
import missingno
import numpy as np
import pandas as pd
import pyreadr
import seaborn as sns
import session_info
import upsetplot

### Operando valores faltantes

In [3]:
print(
    None or True,
    None or False,
    None == None,
    None is None,
    # None + True,
    # None / False,
    type(None),
    sep="\n"
)

True
False
True
True
<class 'NoneType'>

#### Numpy

In [18]:
print(
    np.nan or True,
    np.nan or False,
    np.nan == np.nan,
    np.nan is np.nan,
    type(np.nan),
    np.isnan(np.nan),
    sep = "\n"
)

nan
nan
False
True
<class 'float'>
True

#### Pandas

In [21]:
test_missing_df = pd.DataFrame.from_dict(
    data=dict(
        x=[0, 1, np.nan, np.nan, None],
        y=[0, 1, pd.NA, np.nan, None]
    )
)

test_missing_df

     x     y
0  0.0     0
1  1.0     1
2  NaN  <NA>
3  NaN   NaN
4  NaN  None

In [22]:
test_missing_df.isna()

       x      y
0  False  False
1  False  False
2   True   True
3   True   True
4   True   True

In [24]:
test_missing_df.y.isnull()

0    False
1    False
2     True
3     True
4     True
Name: y, dtype: bool

In [26]:
pd.Series([0, 1, np.nan, np.nan, None])

0    0.0
1    1.0
2    NaN
3    NaN
4    NaN
dtype: float64